### ISSUE TITLE
Linear fit for normalization

### ISSUE THREAD

**Issue by remi-pr** [donaldsonlab/PhAT#15]
While looking at the paper I noticed that the linear fit used to rescale the isosbestic signal to the physiology signal seemed to dampen it quite a lot. 

I am wondering if the fit done at this line https://github.com/donaldsonlab/PhAT/blob/c7c898eca4b3f685dc02c08e29cab2fa482fa661/FiberPho_Main/FiberClass.py#L718
is not done with the reference and signal switched around. I am guessing that if both were to be switched, the output of the fit would bring the reference closer to the signal. Let me know if I am not clear enough.

**Comment by kamu7656** [comment]
Thank you so much for catching this issue!! The change will be pushed soon.
