### ISSUE TITLE
Naming discrepancies and script error

### ISSUE THREAD

**Issue by MicTott** [donaldsonlab/PhAT#2]
Hi all, thank you for developing this package! While following the directions on github for Mac there are a few inconsistencies I noticed, and unfortunately an error when I tried to run the script.  

After downloading the repository, I had to move the `requirements.txt`  from `/PhAT_Main` to `/PhAT_Main/FiberPho_Main` . The given command line function in the instructions calls `FiberGuiScript.py`, but the script name that is downloaded is `PhAT_gui_script.py`. After fixing these things, the server runs but I'm immediately presented with the following errors:

```
NameError: name 'zscore_card' is not defined
Traceback (most recent call last):
  File "/Users/mtotty2/opt/anaconda3/envs/phat/lib/python3.9/site-packages/bokeh/application/handlers/code_runner.py", line 231, in run
    exec(self._code, module.__dict__)
  File "/Users/mtotty2/Documents/Python/PhAT/PhAT-main/FiberPho_Main/PhAT_gui_script.py", line 1498, in <module>
    material.main.append(zscore_card)
```

I have not tried the Jupyter notebook yet.

**Comment by kamu7656** [comment]
Hi,

Thank you so much for the feedback. I believe all these issues have been addressed. Please feel free to reach out with any other concerns. You can also contact me directly by email.  

We have recently published a detailed protocol that describes how to use and modify the software. https://www.biorxiv.org/content/10.1101/2023.03.14.532489v1.full

Best,
Kathleen Murphy
