### ISSUE TITLE
"shortest_list" is not defined

### ISSUE THREAD

**Issue by MicTott** [donaldsonlab/PhAT#4]
Thanks for the previous fix - the GUI is running for me now! 

Unfortunately, when attempting to create a fiber object using the "alternative" format with columns "Timestamp", "Green", and "Isosbestic" I receive the following error: 

> 2023-03-27 13:59:10,638 [ERROR]: Traceback (most recent call last):
>   File "/Users/mtotty2/Documents/Python/PhAT/PhAT-main/FiberPho_Main/PhAT_gui_script.py", line 133, in run_init_fiberobj
>     new_obj = fc.FiberObj(df, input_params[0], input_params[1],
>   File "/Users/mtotty2/Documents/Python/PhAT/PhAT-main/FiberPho_Main/FiberClass.py", line 155, in __init__
>     self.csv__init__(time_slice)
>   File "/Users/mtotty2/Documents/Python/PhAT/PhAT-main/FiberPho_Main/FiberClass.py", line 279, in csv__init__
>     data_dict[channel] = data_dict[channel][:shortest_list-1]
> NameError: name 'shortest_list' is not defined

**Comment by kamu7656** [comment]
I saw your pull request and merged it. Thank you again for finding this bug!
