### ISSUE TITLE
Error loading alternative behavior files

### ISSUE THREAD

**Issue by MicTott** [donaldsonlab/PhAT#6]
I'm currently get the same error when trying to load behavioral data for the alternative file types using both the sample data and my own data. 

>  2023-03-27 17:16:24,584 [ERROR]: Traceback (most recent call last):
>   File "/Users/mtotty2/Documents/Python/PhAT/FiberPho_Main/PhAT_gui_script.py", line 716, in run_convert_alt_beh
>     beh_data = fc.alt_to_boris(alt_beh_file, time_unit.value, beh_false.value,
>   File "/Users/mtotty2/Documents/Python/PhAT/FiberPho_Main/FiberClass.py", line 1490, in alt_to_boris
>     stops.concat((trimmed.iloc[i]['Time']
> AttributeError: 'list' object has no attribute 'concat'

**Comment by kamu7656** [comment]
There was a bug in the alt_to_boris conversion function and I've fixed that. A side note is that the sample alternative behavior file included is in seconds not milliseconds and I have updated the default value to match that.
